### ISSUE TITLE
安装后直接报错,打开链接

### ISSUE THREAD

**Issue by uniteweiwei** [Sparkinzy/dcat-extension-client#2]
![image](https://user-images.githubusercontent.com/19373139/212456224-8a7a0ddf-996a-40c8-9d48-f68d5a2804d1.png)
![image](https://user-images.githubusercontent.com/19373139/212456606-1e072725-bc37-415e-a8e5-ff06156b47a0.png)
dcat-admin版本是2.*,能看到扩展,也能启用,
![image](https://user-images.githubusercontent.com/19373139/212456631-9eed5a03-8d12-469a-87da-02e0af17e316.png)
打开默认链接直接报错

**Comment by zhang11984011** [comment]
我的也是这个情况，但是在win10本地测试环境下安装就没有这个问题。

**Comment by Sparkinzy** [comment]
检查一下自己的php版本,推荐php7.4 或php8

**Comment by zhang11984011** [comment]
我的是7.2
